application: bristoluni-ad-1444
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
  login: optional

- url: /img/.*
  script: main.app
  login: optional

- url: /static/.*
  script: main.app
  login: optional

- url: .*
  script: main.app
  login: required
  auth_fail_action: redirect

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"
